/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uc9.aluno;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EDUARDOEVERTONRODRIG
 */
public class Selecao extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private DefaultTableModel Grifinoria;
    private DefaultTableModel Sonserina;
    private DefaultTableModel LufaLufa;
    private DefaultTableModel Corvinal;
    
    /**
     * Creates new form Selecao
     */
    public Selecao() {
        initComponents();
           
        
         tableModel = new DefaultTableModel();
         Grifinoria = new DefaultTableModel();
         Sonserina = new DefaultTableModel();
         LufaLufa = new DefaultTableModel();
         Corvinal = new DefaultTableModel();
         
         
         
         
       // selecao
        tableModel.addColumn("Nome"); // adiciona uma coluna, ja com o titulo
        tableModel.addColumn("Personalidade");
        
        tableModel.addRow(new Object[]{"Roberto","Corajoso"});//adiciona uma linha, com os valores
        tableModel.addRow(new Object[]{"Fulano","Astuto"});
        tableModel.addRow(new Object[]{"Everton","Leal"});
        tableModel.addRow(new Object[]{"Jao","Inteligente"});
        
        tableSelecao.setModel(tableModel);
         
        
        
        
       // grifinoria 
         tableGrifinoria.setModel(Grifinoria);
         
        Grifinoria.addColumn("Nome"); // adiciona uma coluna, ja com o titulo
        Grifinoria.addColumn("Personalidade");
         
        
        
        
       // Sonseria
       tableSonserina.setModel(Sonserina);
         
        Sonserina.addColumn("Nome"); // adiciona uma coluna, ja com o titulo
        Sonserina.addColumn("Personalidade");
        
        
        
        
        
       // Lufa-Lufa
        tableLufaLufa.setModel(LufaLufa);
         
        LufaLufa.addColumn("Nome"); // adiciona uma coluna, ja com o titulo
        LufaLufa.addColumn("Personalidade");
       
        
        
        
       // Corvinal
       tableCorvinal.setModel(Corvinal);
         
        Corvinal.addColumn("Nome"); // adiciona uma coluna, ja com o titulo
        Corvinal.addColumn("Personalidade");
         

        
        
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSelecao = new javax.swing.JTable();
        labelAlunos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCorvinal = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableLufaLufa = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableGrifinoria = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableSonserina = new javax.swing.JTable();
        labelGrifinoria = new javax.swing.JLabel();
        labelSonserina = new javax.swing.JLabel();
        labelLufaLufa = new javax.swing.JLabel();
        labelCorvinal = new javax.swing.JLabel();
        btnExpulsar = new javax.swing.JButton();
        btnChapeuSeletor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        tableSelecao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Personalidade"
            }
        ));
        jScrollPane1.setViewportView(tableSelecao);

        labelAlunos.setForeground(new java.awt.Color(51, 51, 0));
        labelAlunos.setText("Recem Chegados");

        tableCorvinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Personalidade"
            }
        ));
        jScrollPane2.setViewportView(tableCorvinal);

        tableLufaLufa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Personalidade"
            }
        ));
        jScrollPane3.setViewportView(tableLufaLufa);

        tableGrifinoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Personalidade"
            }
        ));
        jScrollPane4.setViewportView(tableGrifinoria);

        tableSonserina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Personalidade"
            }
        ));
        jScrollPane5.setViewportView(tableSonserina);

        labelGrifinoria.setForeground(new java.awt.Color(51, 51, 0));
        labelGrifinoria.setText("Alunos Grifinoria");

        labelSonserina.setForeground(new java.awt.Color(51, 51, 0));
        labelSonserina.setText("Alunos Sonserina");

        labelLufaLufa.setForeground(new java.awt.Color(51, 51, 0));
        labelLufaLufa.setText("Alunos Lufa-Lufa");

        labelCorvinal.setForeground(new java.awt.Color(51, 51, 0));
        labelCorvinal.setText("Alunos Corvinal");

        btnExpulsar.setBackground(new java.awt.Color(255, 255, 255));
        btnExpulsar.setForeground(new java.awt.Color(153, 153, 0));
        btnExpulsar.setText("Expulsar");
        btnExpulsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpulsarActionPerformed(evt);
            }
        });

        btnChapeuSeletor.setBackground(new java.awt.Color(255, 255, 255));
        btnChapeuSeletor.setForeground(new java.awt.Color(153, 153, 0));
        btnChapeuSeletor.setText("Chapéu Seletor");
        btnChapeuSeletor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChapeuSeletorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelLufaLufa)
                .addGap(228, 228, 228)
                .addComponent(labelCorvinal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnChapeuSeletor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExpulsar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelAlunos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(labelGrifinoria)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(labelSonserina)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelAlunos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnExpulsar)
                                    .addComponent(btnChapeuSeletor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(labelGrifinoria))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelSonserina)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(labelLufaLufa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelCorvinal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExpulsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpulsarActionPerformed
       
         //Pega o índice do item selecionado na lista da minha Selecao
        int index = tableSelecao.getSelectedRow();
        
        //Se eu não selecionei nada ainda, ele mostra uma janela que contém a mensagem abaixo
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Aluno da selecao!");
            return;
        }
      
        // Aqui, eu removo o pokemon do ArrayList mochila
        tableSelecao.remove(index);
        
        
       

        
    }//GEN-LAST:event_btnExpulsarActionPerformed

    private void btnChapeuSeletorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChapeuSeletorActionPerformed
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnChapeuSeletorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChapeuSeletor;
    private javax.swing.JButton btnExpulsar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelAlunos;
    private javax.swing.JLabel labelCorvinal;
    private javax.swing.JLabel labelGrifinoria;
    private javax.swing.JLabel labelLufaLufa;
    private javax.swing.JLabel labelSonserina;
    private javax.swing.JTable tableCorvinal;
    private javax.swing.JTable tableGrifinoria;
    private javax.swing.JTable tableLufaLufa;
    private javax.swing.JTable tableSelecao;
    private javax.swing.JTable tableSonserina;
    // End of variables declaration//GEN-END:variables
}
