/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uc9.Calculadora;

/**
 *
 * @author EDUARDOEVERTONRODRIG
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRosa = new javax.swing.JPanel();
        campoNumero1 = new javax.swing.JTextField();
        campoNumero2 = new javax.swing.JTextField();
        PanelVermelho = new javax.swing.JPanel();
        ButtonMultiplicacao = new javax.swing.JButton();
        ButtonDivisao = new javax.swing.JButton();
        ButtonSoma = new javax.swing.JButton();
        ButtonSubtracao = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();
        LabelCalculadora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        PanelRosa.setBackground(new java.awt.Color(255, 204, 204));

        campoNumero1.setBackground(new java.awt.Color(255, 255, 255));
        campoNumero1.setForeground(new java.awt.Color(153, 0, 0));
        campoNumero1.setText("Insira o numero 1");
        campoNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumero1ActionPerformed(evt);
            }
        });

        campoNumero2.setBackground(new java.awt.Color(255, 255, 255));
        campoNumero2.setForeground(new java.awt.Color(153, 0, 0));
        campoNumero2.setText("Insira o numero 2");
        campoNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumero2ActionPerformed(evt);
            }
        });

        PanelVermelho.setBackground(new java.awt.Color(153, 0, 0));

        ButtonMultiplicacao.setBackground(new java.awt.Color(255, 255, 255));
        ButtonMultiplicacao.setForeground(new java.awt.Color(153, 0, 0));
        ButtonMultiplicacao.setText("Multiplicacao");
        ButtonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplicacaoActionPerformed(evt);
            }
        });

        ButtonDivisao.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDivisao.setForeground(new java.awt.Color(153, 0, 0));
        ButtonDivisao.setText("Divisao");
        ButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDivisaoActionPerformed(evt);
            }
        });

        ButtonSoma.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSoma.setForeground(new java.awt.Color(153, 0, 0));
        ButtonSoma.setText("Soma");
        ButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSomaActionPerformed(evt);
            }
        });

        ButtonSubtracao.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSubtracao.setForeground(new java.awt.Color(153, 0, 0));
        ButtonSubtracao.setText("Subtracao");
        ButtonSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubtracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVermelhoLayout = new javax.swing.GroupLayout(PanelVermelho);
        PanelVermelho.setLayout(PanelVermelhoLayout);
        PanelVermelhoLayout.setHorizontalGroup(
            PanelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVermelhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelVermelhoLayout.createSequentialGroup()
                        .addComponent(ButtonSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(ButtonDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelVermelhoLayout.createSequentialGroup()
                        .addComponent(ButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelVermelhoLayout.setVerticalGroup(
            PanelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVermelhoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonMultiplicacao)
                    .addComponent(ButtonSoma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDivisao)
                    .addComponent(ButtonSubtracao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelResultado.setBackground(new java.awt.Color(255, 255, 255));
        labelResultado.setForeground(new java.awt.Color(153, 0, 0));
        labelResultado.setText("Resultado: ");

        LabelCalculadora.setFont(new java.awt.Font("SimSun-ExtG", 3, 18)); // NOI18N
        LabelCalculadora.setForeground(new java.awt.Color(204, 0, 0));
        LabelCalculadora.setText("CALCULADORA");

        javax.swing.GroupLayout PanelRosaLayout = new javax.swing.GroupLayout(PanelRosa);
        PanelRosa.setLayout(PanelRosaLayout);
        PanelRosaLayout.setHorizontalGroup(
            PanelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanelRosaLayout.createSequentialGroup()
                .addGroup(PanelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRosaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(campoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRosaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(PanelVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRosaLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(PanelRosaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelCalculadora)
                .addGap(172, 172, 172))
        );
        PanelRosaLayout.setVerticalGroup(
            PanelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRosaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabelCalculadora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelResultado)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelRosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRosa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumero1ActionPerformed

    private void campoNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumero2ActionPerformed

    private void ButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSomaActionPerformed
           Double num1 = Double.parseDouble(campoNumero1.getText());
           Double num2 = Double.parseDouble(campoNumero2.getText());
           
          labelResultado.setText("Resultado." + (num1 + num2));

    }//GEN-LAST:event_ButtonSomaActionPerformed

    private void ButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDivisaoActionPerformed
       Double num1 = Double.parseDouble(campoNumero1.getText());
           Double num2 = Double.parseDouble(campoNumero2.getText());
           
          labelResultado.setText("Resultado." + (num1 / num2)); 
    }//GEN-LAST:event_ButtonDivisaoActionPerformed

    private void ButtonSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubtracaoActionPerformed
          Double num1 = Double.parseDouble(campoNumero1.getText());
           Double num2 = Double.parseDouble(campoNumero2.getText());
           
          labelResultado.setText("Resultado." + (num1 - num2)); 
    }//GEN-LAST:event_ButtonSubtracaoActionPerformed

    private void ButtonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplicacaoActionPerformed
         Double num1 = Double.parseDouble(campoNumero1.getText());
           Double num2 = Double.parseDouble(campoNumero2.getText());
           
          labelResultado.setText("Resultado." + (num1 * num2)); 
    }//GEN-LAST:event_ButtonMultiplicacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDivisao;
    private javax.swing.JButton ButtonMultiplicacao;
    private javax.swing.JButton ButtonSoma;
    private javax.swing.JButton ButtonSubtracao;
    private javax.swing.JLabel LabelCalculadora;
    private javax.swing.JPanel PanelRosa;
    private javax.swing.JPanel PanelVermelho;
    private javax.swing.JTextField campoNumero1;
    private javax.swing.JTextField campoNumero2;
    private javax.swing.JLabel labelResultado;
    // End of variables declaration//GEN-END:variables
}
