/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uc9.eventos;

import java.awt.event.KeyEvent;

/**
 *
 * @author EDUARDOEVERTONRODRIG
 */
public class Evento extends javax.swing.JFrame {

    /**
     * Creates new form Evento
     */
    public Evento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonCliqueEmMim1 = new javax.swing.JButton();
        ButtonCliqueEmMim2 = new javax.swing.JButton();
        ButtonCliqueEmMim3 = new javax.swing.JButton();
        TxtEnter = new javax.swing.JTextField();
        ButtonTenteClicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        ButtonCliqueEmMim1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonCliqueEmMim1.setForeground(new java.awt.Color(153, 0, 0));
        ButtonCliqueEmMim1.setText("Clique em mim");
        ButtonCliqueEmMim1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCliqueEmMim1MouseClicked(evt);
            }
        });
        ButtonCliqueEmMim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCliqueEmMim1ActionPerformed(evt);
            }
        });

        ButtonCliqueEmMim2.setBackground(new java.awt.Color(255, 255, 255));
        ButtonCliqueEmMim2.setForeground(new java.awt.Color(153, 0, 0));
        ButtonCliqueEmMim2.setText("Clique em mim");

        ButtonCliqueEmMim3.setBackground(new java.awt.Color(255, 255, 255));
        ButtonCliqueEmMim3.setForeground(new java.awt.Color(153, 0, 0));
        ButtonCliqueEmMim3.setText("Clique em mim");
        ButtonCliqueEmMim3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ButtonCliqueEmMim3FocusGained(evt);
            }
        });
        ButtonCliqueEmMim3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonCliqueEmMim3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonCliqueEmMim3MouseExited(evt);
            }
        });

        TxtEnter.setBackground(new java.awt.Color(153, 0, 0));
        TxtEnter.setForeground(new java.awt.Color(255, 255, 255));
        TxtEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEnterActionPerformed(evt);
            }
        });
        TxtEnter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtEnterKeyPressed(evt);
            }
        });

        ButtonTenteClicar.setText("Tente clicar em mim");
        ButtonTenteClicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonTenteClicarMouseEntered(evt);
            }
        });
        ButtonTenteClicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTenteClicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(ButtonCliqueEmMim2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(ButtonCliqueEmMim3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(ButtonCliqueEmMim1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(TxtEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(ButtonTenteClicar)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(ButtonCliqueEmMim1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonCliqueEmMim2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCliqueEmMim3)
                .addGap(11, 11, 11)
                .addComponent(TxtEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ButtonTenteClicar)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCliqueEmMim3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ButtonCliqueEmMim3FocusGained
     
    }//GEN-LAST:event_ButtonCliqueEmMim3FocusGained

    private void TxtEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEnterActionPerformed
    
    }//GEN-LAST:event_TxtEnterActionPerformed

    private void TxtEnterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEnterKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          System.out.println("Enter foi pressionado!");
    }
    }//GEN-LAST:event_TxtEnterKeyPressed

    private void ButtonCliqueEmMim3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCliqueEmMim3MouseEntered
       
           System.out.println("Cursor entrou no elemento");
    }//GEN-LAST:event_ButtonCliqueEmMim3MouseEntered

    private void ButtonCliqueEmMim3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCliqueEmMim3MouseExited

        System.out.println("Cursor saiu no elemento");
    }//GEN-LAST:event_ButtonCliqueEmMim3MouseExited

    private void ButtonCliqueEmMim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCliqueEmMim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCliqueEmMim1ActionPerformed

    private void ButtonCliqueEmMim1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCliqueEmMim1MouseClicked

    }//GEN-LAST:event_ButtonCliqueEmMim1MouseClicked

    private void ButtonTenteClicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTenteClicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTenteClicarActionPerformed

    private void ButtonTenteClicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonTenteClicarMouseEntered
        int maxX = this.getWidth() - ButtonTenteClicar.getWidth();
        int maxY = this.getHeight() - ButtonTenteClicar.getHeight();

        int x = (int) (Math.random() * maxX);
        int y = (int) (Math.random() * maxY);
        
        ButtonTenteClicar.setLocation(x,y);
    }//GEN-LAST:event_ButtonTenteClicarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCliqueEmMim1;
    private javax.swing.JButton ButtonCliqueEmMim2;
    private javax.swing.JButton ButtonCliqueEmMim3;
    private javax.swing.JButton ButtonTenteClicar;
    private javax.swing.JTextField TxtEnter;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
